// This file is generated by Slice Machine. Update with care!

import AlgoliaSearch from './AlgoliaSearch';
import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	AlgoliaSearch,
	ContactForm,
	Image,
	Quote,
	Text,
};

export const components = {
	algolia_search: AlgoliaSearch,
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	text: Text,
};
